version: '3.8'

name: nft-bidding-platform

services:
  auth-db:
    image: mongo
    container_name: auth-db
    ports:
      - 27015:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  nft-db:
    image: mongo
    container_name: nft-db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  user-db:
    image: mongo
    container_name: user-db
    ports:
      - 27021:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  inventory-db:
    image: mongo
    container_name: inventory-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  payment-db:
    image: mongo
    container_name: payment-db
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  redis-db:
    image: redis
    restart: always
    container_name: redis-db
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=123456

